<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/2.%20numpy_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
print(x)

y = np.array([[2, 3, 4], [1, 2, 5]])
print(y)

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


1. np.arange 함수로 생성하기

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(5, 101, 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

np.arange 함수의 경우 (시작값, 종료값+1, 두 값 사이의 간격) 으로 표현됨.

2. np.ones, np.zeros로 생성하기

In [9]:
np.ones((1,10)) #1로만 생성

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.zeros(10) #0으로만 생성

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((2, 5, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

3. np.empty, np.full 생성

In [13]:
np.empty(10) #초기화된 값을 가지기 위함

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.full((3, 4), 7) #7로된 값을 3 * 4 사이즈로 갖기

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

4. np.eye로 생성 - 단위행렬 생성

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

5. np.linspace로 생성

In [16]:
np.linspace(1, 10, 3) # 1부터 10까지의 수를 3으로 균등하게 나누어 값을 도출

array([ 1. ,  5.5, 10. ])

In [17]:
np.linspace(2, 10, 3)

array([ 2.,  6., 10.])

6. reshape 함수 활용

In [18]:
x = np.arange(1, 16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [19]:
x.reshape(3, 5) # 3 * 5 사이즈로 변경

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

주의 : reshape 시 행과 열을 곱한 수가 전체 수와 같도록 해야함.