<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/3.%20random_%EC%84%9C%EB%B8%8C_%EB%AA%A8%EB%93%88_%ED%95%A8%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

random 서브모듈

rand 함수
* 0, 1 사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(2, 3) # 2 * 3의 랜덤한 어레이 생성

array([[0.84644353, 0.9362827 , 0.33930208],
       [0.64771587, 0.26516689, 0.80778975]])

In [3]:
np.random.rand(10)

array([0.08554387, 0.19059372, 0.63643892, 0.35493931, 0.38761251,
       0.40624856, 0.04016373, 0.73350394, 0.53001687, 0.25911621])

In [4]:
np.random.rand(2, 4, 3) # 3차원 어레이 생성

array([[[0.01711848, 0.18283171, 0.73918545],
        [0.63017284, 0.71070164, 0.00822831],
        [0.02668933, 0.83417828, 0.72971598],
        [0.54930026, 0.26511703, 0.43428742]],

       [[0.42768458, 0.72464756, 0.217803  ],
        [0.43183675, 0.31415312, 0.90490773],
        [0.41611554, 0.09757239, 0.84728996],
        [0.31136066, 0.05149764, 0.91009582]]])

randn함수
* n: normal distribution (정규분포)
* 정규분포로 샘플링된 랜덤 ndarray 생성

In [5]:
np.random.randn(3, 4)

array([[ 0.49386353,  1.28131478, -0.37859092, -1.11756161],
       [ 1.15669724,  1.04283037,  2.63308597,  1.30836879],
       [-0.68953363,  1.31044629, -0.86940709,  0.0565605 ]])

In [6]:
np.random.randn(10)

array([ 0.56226244, -0.42332959,  0.80107585, -0.8717087 ,  0.2734139 ,
        0.11127298,  0.67923531,  0.80604259,  1.41107769, -0.84043537])

randint 함수
* 특정 정수 사이에서 랜덤하게 샘플링

In [9]:
np.random.randint(1, 10, size=(3, 4)) # 1부터 10까지 수 중 랜덤하게 3 * 4 형태로 배열하는 것

array([[6, 4, 1, 5],
       [3, 5, 5, 5],
       [6, 1, 1, 5]])

seed 함수
* 랜덤한 값을 동일하게 다시 생성하고자 할 때 사용

In [13]:
np.random.seed(10) # 랜덤한 수를 주지만, 동일하게 다시 생성할 수 있도록 함. 단독적으로 사용 불가능 - randn 함수 또는 randint 등과 함께 사용
np.random.randn(3, 4)

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556,  0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021,  0.43302619,  1.20303737]])

choice 함수
* 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
* 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [14]:
np.random.choice(100, size=(3, 4)) #1부터 100까지 수 중 랜덤하게 3 * 4 사이즈로 배열, 같은 수 중복 가능

array([[72, 78, 49, 51],
       [54, 77, 69, 13],
       [25, 13, 92, 86]])

In [16]:
np.random.choice(100, size=(3, 4), replace=False) #같은 수 중복 불가능

array([[75, 64, 41, 13],
       [ 8, 70, 92, 59],
       [79, 98, 67, 24]])

In [19]:
x = np.array([1, 3, 5, 2.5, 4.6, 7.1])
np.random.choice(x, size=(3, 4))

array([[1. , 5. , 2.5, 2.5],
       [2.5, 5. , 7.1, 5. ],
       [2.5, 1. , 7.1, 7.1]])

In [21]:
x = np.array([1, 3, 5, 2.5, 4.6, 7.1])
np.random.choice(x, size=(2, 2), replace=False) #같은 수 중복 불가능

array([[1. , 4.6],
       [5. , 3. ]])