<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/4.%20ndarray_%EC%9D%B8%EB%8D%B1%EC%8B%B1_%26_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

인덱싱
* 파이썬 리스트와 동일한 개념으로 사용
* ,를 사용하여 각 차원의 인덱스에 접근 가능

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
x[-1]

9

In [5]:
x[3] = 100 # list와 같이 인덱싱 가능
print(x)

[  0   1   2 100   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [10]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
# 두번째줄 숫자 7을 호출하는 경우
x[1, 2]

7

* 3차원 행렬 인덱싱

In [12]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [13]:
# 두번째 행렬의 세번째줄 숫자 19를 호출하는 경우
x[1, 2, 1]

19

* 2차원 행렬 슬라이싱

In [14]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
# 전체 행 중 1,2,3번째 수만 호출하는 경우
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [17]:
# 두번째 행 중 3,4번째 수만 호출하는 경우
x[1, 2:4]

array([7, 8])

* 3차원 텐서 슬라이싱

In [20]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [21]:
# 세번째 행렬 중 2번째 행, 전체 수를 호출하는 경우
x[2, 1, :]

array([27, 28, 29])

In [22]:
# 전체 행렬 중 각 3번째 행, 2,3번째 수를 호출하는 경우
x[:, 2, 1:3]

array([[ 7,  8],
       [19, 20],
       [31, 32]])