<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/5.%20ndarray_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%98%95%ED%83%9C%EB%A5%BC_%EB%B0%94%EA%BF%94%EB%B3%B4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

ravel, np.ravel
* 다차원배열을 1차원으로 변경
* 'order'파라미터
* 'C' - row 순서 
  * ex) np.ravel(x, order='C')
* 'F' - column 순서
  * ex) np.ravel(x, order='F') 

In [3]:
x = np.arange(15).reshape(3, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

flatten
* 다차원배열을 1차원으로 변경
*'order' 파라미터
* 'C' - row 순서
* 'F' - column 순서

In [7]:
y = np.arange(15).reshape(3, 5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* 차이점 비교

In [10]:
temp = x.ravel()
temp[0] = 100
print(temp)
print(x)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [11]:
temp2 = y.flatten()
temp2[0] = 100
print(temp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


* ravel과의 차이점: copy를 생성하여 변경함 - 원본 데이커가 아닌 복사본을 반환함

In [12]:
print(x.ndim) #배열 차원을 나타냄
print(y.ndim)

2
2
