<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/6.%20ndarray_%EA%B8%B0%EB%B3%B8_%ED%95%A8%EC%88%98_%EC%82%AC%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.66214669 0.94138597 0.39962892 0.24794237 0.72370598]
 [0.01861908 0.02053765 0.65116051 0.17870899 0.12197446]
 [0.97855763 0.53560837 0.00497677 0.10770079 0.03388926]]


연산 함수
* add, subtract, multiply, divide

In [4]:
np.add(x, y) #더하기

array([[ 0.66214669,  1.94138597,  2.39962892,  3.24794237,  4.72370598],
       [ 5.01861908,  6.02053765,  7.65116051,  8.17870899,  9.12197446],
       [10.97855763, 11.53560837, 12.00497677, 13.10770079, 14.03388926]])

In [5]:
np.subtract(x, y) #빼기

array([[-0.66214669,  0.05861403,  1.60037108,  2.75205763,  3.27629402],
       [ 4.98138092,  5.97946235,  6.34883949,  7.82129101,  8.87802554],
       [ 9.02144237, 10.46439163, 11.99502323, 12.89229921, 13.96611074]])

In [6]:
np.multiply(x, y) #곱하기

array([[0.        , 0.94138597, 0.79925785, 0.7438271 , 2.8948239 ],
       [0.09309538, 0.12322588, 4.55812359, 1.42967191, 1.09777016],
       [9.78557633, 5.89169205, 0.05972118, 1.40011025, 0.4744496 ]])

In [7]:
np.divide(x, y) #나누기

array([[0.00000000e+00, 1.06226354e+00, 5.00464277e+00, 1.20995861e+01,
        5.52710650e+00],
       [2.68541801e+02, 2.92146431e+02, 1.07500376e+01, 4.47655154e+01,
        7.37859370e+01],
       [1.02191222e+01, 2.05373938e+01, 2.41120471e+03, 1.20704780e+02,
        4.13110262e+02]])

통계 함수
* 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련 함수 내장

In [8]:
np.mean(y) #평균
y.mean()

0.3751028948211523

In [9]:
np.var(y) #분산
np.median(y) #중앙
np.average(y) # 평균
np.max(y) #최대
np.min(y) #최소

0.004976765329011701

In [10]:
np.std(y) #표준편차

0.3354459039051996

집계함수
* 합계(sum), 누적합계(cumsum) 등등 계산가능

In [11]:
y

array([[0.66214669, 0.94138597, 0.39962892, 0.24794237, 0.72370598],
       [0.01861908, 0.02053765, 0.65116051, 0.17870899, 0.12197446],
       [0.97855763, 0.53560837, 0.00497677, 0.10770079, 0.03388926]])

In [12]:
np.sum(y)

5.626543422317284

In [13]:
np.cumsum(y) #누적합계

array([0.66214669, 1.60353266, 2.00316158, 2.25110395, 2.97480992,
       2.993429  , 3.01396664, 3.66512716, 3.84383615, 3.96581061,
       4.94436824, 5.47997661, 5.48495338, 5.59265416, 5.62654342])

In [17]:
np.sum(y, axis=1) #가로 합

array([2.97480992, 0.99100069, 1.66073281])

In [18]:
np.sum(y, axis=0) #세로 합

array([1.65932339, 1.49753199, 1.0557662 , 0.53435214, 0.8795697 ])

where 함수
* 조건에 따라 선별적으로 값을 선택 가능
* 사용 예) 음수인 경우는 0, 나머지는 그대로 값을 쓰는 경우 

In [19]:
z = np.random.rand(10)
print(z)

[0.92308368 0.58779713 0.15533372 0.98493444 0.47487286 0.20402253
 0.14743121 0.90678279 0.13797246 0.67837333]


In [20]:
np.where(z > 0, z, 0) #(조건, 참일 때 출력값, 거짓일 때 출력값)

array([0.92308368, 0.58779713, 0.15533372, 0.98493444, 0.47487286,
       0.20402253, 0.14743121, 0.90678279, 0.13797246, 0.67837333])