<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/7.%20axis%EC%B6%95_%EC%9D%B4%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
np.sum(x, axis=0) #1차원 벡터의 경우, 축이 하나밖에 없음

45

In [5]:
y = x.reshape(2, 5)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
np.sum(y, axis=0) #세로축 방향으로 합

array([ 5,  7,  9, 11, 13])

In [7]:
np.sum(y, axis=1) #가로축 방향으로 합

array([10, 35])

In [8]:
z = np.arange(36).reshape(3, 4, 3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [9]:
np.sum(z, axis=0) # (4, 3) 형태의 벡터로 출력

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [10]:
np.sum(z, axis=1) # (3, 3) 형태의 벡터로 출력

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [11]:
np.sum(z, axis=2) # (3, 4) 형태의 벡터로 출력

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])