<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/8.%20Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Boolean indexing
* ndarray 인덱싱 시, bool 리스트를 전달하여 true인 경우만 필터링
* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
* 예) 짝수인 경우만 찾아보기

In [4]:
x = np.random.randint(1, 100, size=10)
print(x)

[55 19 69 70 46 98 37 76 77 91]


In [7]:
even_mask = x % 2 == 0
print(even_mask)

[False False False  True  True  True False  True False False]


* bool 리스트를 인덱스로 전달

In [9]:
x[even_mask] #true인 값만 반환

array([70, 46, 98, 76])

다중조건 사용하기
* 파이썬 논리 연산지인 and,or,not 키워드 사용불가
* & - AND
* | - OR

In [13]:
print(x)
x % 2 == 0
x < 30

x[(x % 2 == 0) & (x < 30)]

[55 19 69 70 46 98 37 76 77 91]


array([], dtype=int64)

In [14]:
a = x < 30
b = x > 50

x[a | b]

array([55, 19, 69, 70, 98, 76, 77, 91])