<a href="https://colab.research.google.com/github/cedrismjeon/numpy_practice/blob/main/9.%20linalg_%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88_%EC%82%AC%EC%9A%A9%ED%95%9C_%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.linalg.inv
* 역행렬을 구할 때 사용
* 모든 차원의 값이 같아야 함

In [3]:
x = np.random.rand(3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[0.58486869 0.3889494  0.7115659 ]
 [0.060672   0.02542037 0.65397682]
 [0.11135203 0.54505148 0.45244758]]


array([[ 1.00000000e+00,  9.57603318e-17, -9.78502235e-17],
       [ 1.09544033e-17,  1.00000000e+00, -5.15472205e-18],
       [ 4.56735620e-17,  1.38377037e-16,  1.00000000e+00]])

np.linalg.solve
* Ax = B 형태의 선형대수식 솔루션을 제공
* 예제) 호랑이와 홍합의 합 : 25, 호랑이 다리와 홍합 다리의 합은 64
 * x + y = 25
 * 2x + 4y = 64

In [4]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

[18.  7.]
